version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: holiday
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"